### PR TITLE
doc: add boilerplate files

### PR DESCRIPTION
**Pull request by mhdawson**
Add the required governance files for the new project

### CODE REVIEW

**Comment by indutny** [comment]
LGTM

**Comment by mhdawson** [comment]
Landed as 72bc4d697efc9781421d2f52725f374b9e98a59b

**Comment by mhdawson** [comment]
@indutny where you planning to use the same boilerplate files for moving llnode in?  If so you can probably now land them in your repo and then open the issue in the TSC repo to request the final ok for the transfer.

**Comment by indutny** [comment]
@mhdawson good idea! Pushed in https://github.com/indutny/llnode/commit/51efb31

**Pull request closed without merging**
