### PR TITLE
Update README and package.json for NPM publish

### PR DESCRIPTION
**Pull request by rnchamberlain**
Improve README to indicate supported OS and Node.js versions, provide REPL example and clarify usage. Update version and add github links to package.json.

### CODE REVIEW

**Comment by sam-github** [comment]
A rebase onto master will get rid of the merge commit.

**Comment by sam-github** [comment]
Also, there is no git tag for the release, and its not clear why this is a PR

**Comment by rnchamberlain** [comment]
This PR is needed to update nodereport on github to reflect the README and package.json changes that are on https://www.npmjs.com/package/nodereport. I'll redo as a single commit, and add a git tag for the release.

**Comment by sam-github** [comment]
Publishes aren't generally PRed, they are done directly on master, tagged, git pushed, then the git tag is checked out, and then you `npm publish` from the git tag.

You can use something like https://github.com/strongloop/strong-tools#slt-release to do that all for you, with all the changelogs, tags and commits consistent, or do it yourself. Ping me if you want a `slt-release` walk-through.

**Pull request closed without merging**
